### ISSUE TITLE
Issue enabling addon

### ISSUE THREAD

**Issue by Getrad** [GPUOpen-LibrariesAndSDKs/BlenderUSDHydraAddon#95]
When trying to enable the addon using Blender 2.92 or 2.90.1 (suggested: [here](https://github.com/GPUOpen-LibrariesAndSDKs/BlenderUSDHydraAddon/issues/18)) to no avail, with this consistent os module error:
2021-08-25 09:47:39,034 INFO hdusd.init [25700]:  Loading USD Hydra addon version=(1, 0, 21), build=b0bf57e
Traceback (most recent call last):
  File "C:\temp\software\blender_builds\blender_foundation\blender-2.90.1-windows64\2.90\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\xxxxxx\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\hdusd\__init__.py", line 39, in <module>
    from . import engine, properties, ui, usd_nodes, mx_nodes, bl_nodes
  File "C:\Users\xxxxxx\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\hdusd\engine\__init__.py", line 27, in <module>
    os.add_dll_directory(str(utils.LIBS_DIR / 'usd'))
AttributeError: module 'os' has no attribute 'add_dll_directory'

Wrong python version perhaps(?), but no other addons are currently causing issue, so that one seems unlikely.

Any thoughts?

**Comment by bnagirniak** [comment]
This addon works for Blender 2.93+ with python 3.9. We started to not support earlier Blenders for a long time ago.

**Comment by Getrad** [comment]
Thank you, Bogdan!

I see my misunderstanding came from the [landing page](https://github.com/GPUOpen-LibrariesAndSDKs/BlenderUSDHydraAddon), requirements "Currently, this addon works only with Blender 2.90+ and only in Windows."

will try 2.93 and report any new issues.

**Comment by bsavery** [comment]
The latest build should mainly work on 2.93.  We haven't tested on earlier versions.
